### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by 0xRZ** [Beaglefoot/awk-language-server#32]
`npm install "awk-language-server@>=0.5.2"`
fails with:
`npm ERR! gyp: /usr/include/node16/common.gypi not found (cwd: /home/user/.my_tmp/tests/node_modules/tree-sitter-awk) while reading includes of binding.gyp while trying to load binding.gyp`
  

```
❯ npm --version
8.5.0
```
full log:
[2022-05-21T14_47_10_330Z-debug-0.log](https://github.com/Beaglefoot/awk-language-server/files/8747808/2022-05-21T14_47_10_330Z-debug-0.log)

**Comment by Beaglefoot** [comment]
@0xRZ You need Development headers for nodejs.

I'm currently using openSUSE Tumbleweed and in addition to nodejs16 package I also installed **nodejs16-devel**.

You probably have something similar on your repos.

```
$ zypper search -i node
Loading repository data...
Reading installed packages...

S  | Name           | Summary                               | Type
---+----------------+---------------------------------------+--------
i  | nodejs-common  | Common files for the NodeJS ecosystem | package
i+ | nodejs16       | Evented I/O for V8 JavaScript         | package
i+ | nodejs16-devel | Development headers for NodeJS 16.x   | package
```

**Comment by 0xRZ** [comment]
@Beaglefoot yes, it solves the issue, thank you
