### ISSUE TITLE
Incompatibility with node v19.0.0

### ISSUE THREAD

**Issue by IngoMeyer441** [Beaglefoot/awk-language-server#37]
Unfortunately, `awk-language-server` does not run with node >= 19 currently because of its dependency `tree-sitter-awk` in version `0.5.0`. This is fixed in version `0.5.2`, see [issue #9 in the tree-sitter-awk repository](https://github.com/Beaglefoot/tree-sitter-awk/issues/9) as a reference. Could you please upgrade the dependency?

**Comment by Beaglefoot** [comment]
Recently released version 0.9.4 can be installed with node v19 and I tested it with coc plugin for vim, so hopefully it's good to go. Please reopen otherwise.
