### ISSUE TITLE
Multidimensional array index is not recognized

### ISSUE THREAD

**Issue by 0liv1er** [Beaglefoot/awk-language-server#40]
Given the following `test.awk` script:
```
BEGIN {
  array["foo", "bar"] = "hello world"

  print "index [\"foo\"] is" (("foo") in array ? "" : "n't") " part of the array"
  print "index [\"foo\",\"bar\"] is" (("foo", "bar") in array ? "" : "n't") " part of the array"
}
```
The index `("foo", "bar")` provides a `Syntax error` when editing the script with `nvim` and the `awk-language-server` plugin.
The index `("foo")` doesn't show any error.

**Comment by Beaglefoot** [comment]
Thanks for reporting!
It was an overlook in parser which is now fixed.
