### ISSUE TITLE
using [[:space:]] cause the IDE to point out a syntax error

### ISSUE THREAD

**Issue by m-schwob** [Beaglefoot/awk-language-server#59]
using [[:space:]] cause the IDE to point out a syntax error

code example:

/^[[:space:]]*\/\*/ { # if starts with open comment
    print "syntax error won't break me";
}

the code run fine on Gawk-3.1.6 for Windows

**Comment by Beaglefoot** [comment]
It's not implemented on parser side.
https://github.com/Beaglefoot/tree-sitter-awk/issues/21

**Comment by Beaglefoot** [comment]
This is fixed in version 0.10.3
