### ISSUE TITLE
The server reports any text typed as a variable and adds it to the completion menu

### ISSUE THREAD

**Issue by jmdevin** [Beaglefoot/awk-language-server#66]
# Description
Typing any text at all, such as the letter 'j', and then attempting to complete that text will result in the text appearing in the completion menu as a variable, pointlessly cluttering it.

# Steps to reproduce
1. Open an awk file in a text editor with lsp support
2. Type anything (without spaces or non-alphabetic characters)
3. Attempt to complete the text
4. See that the text typed appears in the completion results

I'm encountering this with vim 9.1.0720, using [coc.nvim](https://github.com/neoclide/coc.nvim), and the most up to date awk-language server.

# Expected Behavior
When the user types in text, and that text appears nowhere else, it shouldn't be identified as a variable and reported as a completion item.

# Additional Info
## Server Response
This is the completion response from the server when I typed the letter 'j' in a completely empty file and (auto-)triggered completion:
```
[Trace - 5:56:29 PM] Received response 'textDocument/completion - (1)' in 11ms.
Result: [
    {
        "label": "j",
        "kind": 6,
        "data": {
            "type": 0,
            "symbolInfo": {
                "name": "j",
                "kind": 13,
                "location": {
                    "uri": "file:///home/john/development/awk/awk_programming_language_2ed/example.awk",
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 0
                        },
                        "end": {
                            "line": 0,
                            "character": 1
                        }
                    }
                },
                "containerName": "awk"
            }
        }
    },
    {
        "label": "OFS",
        "kind": 6,
        "data": {
            "type": 1,
            "jsonPath": "builtins.OFS"
        }
    },
    ---- Many other items ----
]

**Comment by jmdevin** [comment]
@Beaglefoot I know you're not spending a lot of time on awk nowadays, but could you give your opinion on how this might be handled? I may have time in the future to make some changes myself, but it would be quite a bit easier if I knew where to start.

**Comment by Beaglefoot** [comment]
According to gawk manual:

> **VARIABLES, RECORDS AND FIELDS**
       AWK variables are dynamic; they come into existence when they are first used.

So this is an expected behavior and won't be fixed.

**Comment by jmdevin** [comment]
Hey @Beaglefoot, thanks for the response. I do agree; this is technically correct behavior. I didn't mean to dispute that when I opened this issue.

However, there are two points I'll make:

1. The completion is actually behaving inconsistently. The server does not always report what you type as a user-defined variable. See this recording (you may need to view it full screen):
[![asciicast](https://asciinema.org/a/rHg5Qny5yRcQZdEwxQOc0plrB.svg)](https://asciinema.org/a/rHg5Qny5yRcQZdEwxQOc0plrB)
For some reason, it reports the individual letter `b` as a variable, but not `be`, `beg`, or `begi`. Similarly, it treats `j` as a variable, but not `jo`. It does again treat `joj` as a variable, but again not `jojo`.

2. Even if this behavior is correct (if it were consistent), it's not useful. When would I want to 'complete' something I just fully typed for the first time? (If it's a snippet, then yes, otherwise, no.) If I type the letter b, and I want to complete the word 'begin', I first have to move down past the letter 'b' in my completion menu to get to the 'begin' entry.
&nbsp;
It might be possible to remove this entry automatically on the client side, but it seems like it would be prone to accidentally removing other valid variables. Any solution would probably also be quite brittle.
